import * as U from './ui.js';
import {searchForm} from './views.js';
const {esc,fmt,date,total,badge,btn,link,notice,panel,table,nameCell,numberCell,label,stats,head,tabs,options,summary,flow,own,scopedRanking}=U;
const precisionNote='<p class="small muted" style="margin-top:12px">Angka ditampilkan 4 desimal agar ringkas; data normalisasi tersimpan 8 desimal. Seluruh nilai berasal dari data dummy.</p>';
export function matrix(c,items,normalized=false){
 return table(['Polsek',...c.D.platforms.map(f=>f.name),normalized?'Rata-rata':'Total'],items.map(row=>[nameCell(row),...(normalized?row.values:row.raw).map(v=>numberCell(v,normalized?4:0)),numberCell(normalized?total(row.values)/6:total(row.raw),normalized?4:0)]));
}
const analysisStats=c=>stats([['Periode',c.period.label,'Periode contoh, bukan data penelitian'],['Polsek','21','Enam fitur tiap Polsek'],['Rekap',fmt(c.period.recaps.length),'Seluruhnya berstatus disetujui'],['Status','Tersimpan','Snapshot dummy untuk pratinjau']]);
export function preprocessing(c){
 const tab=['dataset','normalize','history'].includes(c.tab)?c.tab:'dataset';
 const navigation=tabs('preprocessing',[['dataset','Data & Dataset'],['normalize','Normalisasi Min-Max'],['history','Riwayat']],tab);
 let body='';
 if(tab==='dataset') body=analysisStats(c)+panel('Pembentukan Dataset Bulanan','<div class="panel-body">'+flow(['Rekap Disetujui','Polsek aktif','Jumlah per platform','Snapshot bulanan'])+'<p class="small muted">Snapshot adalah salinan dataset pada suatu periode proses. Riwayat tetap dapat dilihat tanpa menimpa hasil lama.</p><div class="actions" style="margin-top:16px">'+btn('Pratinjau Bentuk Dataset','dataset-preview','','primary')+link('Lihat Normalisasi','preprocessing/normalize')+'</div></div>')+
 panel('Dataset '+c.period.label,matrix(c,c.period.items),'Total enam platform untuk setiap Polsek dari rekap harian dummy.',btn('Ekspor contoh CSV','csv','data-kind="dataset"','tiny'));
 if(tab==='normalize') body=stats([['Sumber','Dataset bulanan','Total aktivitas per platform'],['Metode','Min-Max','Nilai diseragamkan ke skala 0–1'],['Fitur','6','Min / max dihitung per platform'],['Status','Siap K-Means','Hasil normalisasi dummy']])+
 panel('Normalisasi Min-Max','<div class="panel-body">'+flow(['Dataset','Min / Max tiap fitur','Nilai 0–1','Input K-Means'])+'<div class="formula">X′ = (X − Xmin) / (Xmax − Xmin)</div><p class="small muted" style="margin-top:12px">Rentang nol menjadi 0, sesuai implementasi sistem. Hasil di bawah sudah disiapkan dari data dummy; tombol tidak memproses data operasional.</p><div class="actions" style="margin-top:15px">'+btn('Pratinjau Jalankan Normalisasi','normalization-preview')+link('Lihat Implementasi K-Means','kmeans','primary')+'</div></div>')+
 panel('Statistik Min-Max per Fitur',table(['Platform','Minimum','Maksimum','Rentang'],c.D.platforms.map((f,j)=>{const s=c.period.normalization.statistics[j];return [esc(f.name),numberCell(s.minimum),numberCell(s.maximum),numberCell(s.range)]})))+
 panel('Matriks Hasil Normalisasi',matrix(c,c.period.normalization.items,true)+'<div class="panel-body">'+precisionNote+'</div>','Masing-masing Polsek memiliki enam nilai normalisasi.',btn('Ekspor contoh CSV','csv','data-kind="normalized"','tiny'));
 if(tab==='history') body=notice('Pilih suatu snapshot untuk menelusuri dataset serta hasil normalisasi periode tersebut.')+
 panel('Riwayat Dataset',table(['Snapshot','Periode','Ukuran','Sumber','Status','Aksi'],c.D.periods.map(p=>['Dataset dummy '+p.id,esc(p.label),'21 × 6',p.recaps.length+' rekap dummy',badge('Tersimpan','green'),btn('Lihat Dataset','period-view','data-id="'+p.id+'" data-route="preprocessing/dataset"','tiny')])))+
 panel('Riwayat Preprocessing',table(['Hasil','Dataset sumber','Ukuran','Metode','Status','Aksi'],c.D.periods.map(p=>['Normalisasi dummy '+p.id,'Dataset dummy '+p.id,'21 × 6','Min-Max',badge('Selesai','green'),btn('Lihat Hasil','period-view','data-id="'+p.id+'" data-route="preprocessing/normalize"','tiny')])));
 return head(tab==='normalize'?'Normalisasi Min-Max':'Data & Dataset','Menelusuri alur rekap → snapshot dataset → normalisasi.',tab!=='history'?link('Riwayat','preprocessing/history'):'')+navigation+body;
}
function clusterCards(c){
 return '<section class="clusters">'+c.period.result.clusters.map(cl=>{const people=c.period.ranking.filter(r=>r.cluster_number===cl.cluster_number);return '<article class="cluster '+({tinggi:'high',sedang:'medium',rendah:'low'}[cl.cluster_label])+'">'+badge('C'+cl.cluster_number,'blue')+' '+label(cl.cluster_label)+'<strong>'+cl.member_count+'</strong><p>Polsek</p><div class="small muted">'+people.map(p=>esc(p.polsek_name.replace('Polsek ',''))).join(', ')+'</div></article>'}).join('')+'</section>';
}
export function kmeans(c){
 const tab=['overview','normalization','centroids','iterations','results','dbi'].includes(c.tab)?c.tab:'overview',r=c.period.result;
 let body='';
 if(tab==='overview') body=stats([['Objek','21 Polsek','Aktivitas enam platform'],['Cluster','3','Tinggi, sedang, dan rendah'],['Iterasi dummy',String(r.completed_iterations),'Mengikuti data contoh'],['DBI dummy',fmt(r.dbi,5),'Bukan nilai DBI penelitian']])+
 panel('Alur Implementasi K-Means','<div class="panel-body">'+flow(['Normalisasi','Centroid Awal','Iterasi','Hasil Akhir','DBI'])+'<p class="small muted">Semua tahap hasil dapat ditelusuri. Perhitungan di sini adalah contoh hasil generate, bukan proses live pada website asli.</p><div class="actions" style="margin-top:16px">'+btn('Pratinjau Parameter K-Means','kmeans-preview','','primary')+link('Telusuri Hasil','kmeans/centroids')+'</div></div>')+
 panel('Riwayat K-Means',table(['Hasil contoh','Sumber','Cluster','Iterasi','DBI dummy','Status','Aksi'],c.D.periods.map(p=>['K-Means dummy '+p.id,'Normalisasi '+p.id,'3',String(p.result.completed_iterations),numberCell(p.result.dbi,5),badge('Selesai','green'),btn('Lihat Hasil','period-view','data-id="'+p.id+'" data-route="kmeans/results"','tiny')])),'Riwayat berasal dari dua periode data sintetis.');
 if(tab==='normalization') body=panel('Input Normalisasi',matrix(c,c.period.normalization.items,true)+'<div class="panel-body">'+precisionNote+'</div>','Nilai yang sama dengan halaman Preprocessing, bukan dataset baru.',link('Statistik Min-Max','preprocessing/normalize','tiny'));
 if(tab==='centroids'){
  const initial=r.history[0].centroids;
  body=notice('Deterministic Farthest-First: C1 memakai rata-rata terendah; pusat berikutnya dipilih dari titik dengan jarak terdekat-ke-pusat yang paling besar. Semua angka berikut adalah contoh dummy.')+
   panel('Centroid Awal',table(['Cluster','Polsek asal',...c.D.platforms.map(f=>f.name)],Object.entries(r.seed_items).map(([cl,id])=>['C'+cl,nameCell(c.period.items.find(p=>p.dataset_item_id===id)),...initial[cl].map(v=>numberCell(v,4))])),'Nilai pusat awal diambil dari baris normalisasi Polsek yang terpilih.')+
   panel('Dasar Pemilihan','<div class="panel-body">'+summary([['C1','Rata-rata enam fitur normalisasi terendah; tie ditangani deterministik.'],['C2','Jarak kuadrat terjauh dari C1, dengan kandidat yang belum terpilih.'],['C3','Jarak kuadrat terdekat ke C1/C2 yang nilainya paling besar.'],['Penggunaan berikutnya','Ketiga pusat awal menjadi pembanding pada iterasi pertama.']])+precisionNote+'</div>', '',link('Lihat Iterasi','kmeans/iterations','tiny'));
 }
 if(tab==='iterations'){
  const iterations=r.history.filter(h=>h.iteration>0),h=iterations.find(h=>h.iteration===c.iteration)??iterations[0];
  const selector='<label class="small">Lihat iterasi <select id="iteration-select" aria-label="Iterasi" class="btn">'+options(iterations.map(h=>[h.iteration,'Iterasi '+h.iteration]),h.iteration)+'</select></label>';
  body=panel('Proses Iterasi','<div class="panel-body">'+flow(['Centroid','Jarak Euclidean','Penentuan Cluster','Rata-rata anggota','Centroid Baru'])+'</div>','Jarak di tabel dihitung terhadap centroid sebelum pembaruan.',selector)+
   stats([['Iterasi',String(h.iteration),'Dari data dummy'],['Status',h.status,'Kriteria penghentian sistem'],['Perubahan anggota',h.assignment_changes===null?'Awal':String(h.assignment_changes),'Dibanding iterasi sebelumnya'],['Pergeseran maksimum',fmt(h.maximum_shift,6),'Jarak pusat lama ke baru']])+
   panel('Jarak dan Assignment — Iterasi '+h.iteration,table(['Polsek','Jarak C1','Jarak C2','Jarak C3','Cluster'],h.distances.map(row=>[nameCell(row),...Object.values(row.distances).map(v=>numberCell(v,4)),badge('C'+h.assignments[row.dataset_item_id])])),'Cluster berasal dari assignment implementasi, termasuk aturan tie / cluster kosong.')+
   panel('Centroid Sebelum → Sesudah',table(['Cluster','Anggota',...c.D.platforms.map(f=>f.name)],Object.entries(h.centroids_after).map(([cl,values])=>['C'+cl,String(h.member_counts[cl]),...values.map((v,j)=>'<span class="small muted">'+fmt(h.centroids_before[cl][j],4)+' →</span><br><strong>'+fmt(v,4)+'</strong>')])),'Pusat baru merupakan rata-rata nilai anggota tiap cluster.')+
   notice(h.status==='Konvergen'?'Proses berhenti: assignment tidak berubah atau pergeseran maksimum centroid sudah memenuhi toleransi 0,000001.':'Pusat berubah; pusat baru dipakai pada iterasi berikutnya.')+'<div class="actions">'+link('Hasil Akhir','kmeans/results','primary')+'</div>';
 }
 if(tab==='results') body=notice('Kategori menunjukkan tingkat aktivitas publikasi dalam data dummy, bukan kualitas konten atau hasil penelitian.')+clusterCards(c)+
  panel('Hasil Pengelompokan Polsek',table(['Polsek','Cluster','Kategori','Rata-rata normalisasi','Jarak ke pusat','Total publikasi'],c.period.ranking.map(row=>[nameCell(row),badge('C'+row.cluster_number),label(row.cluster_label),numberCell(row.average_normalized_value,4),numberCell(row.distance_to_centroid,4),numberCell(row.activity_total)])),'Assignment dari iterasi terakhir yang telah konvergen.',btn('Ekspor contoh CSV','csv','data-kind="clustering"','tiny'))+
  panel('Centroid Final',table(['Cluster',...c.D.platforms.map(f=>f.name),'Rata-rata'],r.clusters.map(cl=>['C'+cl.cluster_number,...cl.centroid.map(v=>numberCell(v,4)),numberCell(cl.centroid_average,4)])))+
  '<div class="actions">'+link('Lihat Evaluasi DBI','kmeans/dbi')+link('Lihat Ranking','ranking','primary')+'</div>';
 if(tab==='dbi'){
  const d=r.dbi_details,ids=r.clusters.map(cl=>cl.cluster_number).sort();
  body=notice('DBI menilai kekompakan anggota dalam cluster dan pemisahan antarcluster. Nilai showcase berasal dari data sintetis, bukan DBI penelitian.')+
   panel('Evaluasi Davies-Bouldin Index','<div class="panel-body"><div class="eyebrow">HASIL EVALUASI DATA DUMMY</div><div class="dbi-result">'+fmt(r.dbi,8)+'</div><p class="small muted">Nilai rata-rata rasio maksimum setiap cluster. Tidak menggunakan metrik tambahan.</p>'+flow(['Scatter anggota','Jarak antarcentroid','Rasio pasangan','Maksimum per cluster','Rata-rata DBI'])+'</div>')+
   panel('Scatter: Rata-rata Jarak Anggota',table(['Cluster','Jumlah anggota','Jumlah jarak akhir','Scatter Si'],ids.map(id=>{const rows=r.results.filter(x=>x.cluster_number===id);return ['C'+id,String(rows.length),numberCell(total(rows.map(x=>x.distance_to_centroid)),6),numberCell(d.scatter[id],6)]})),'Si = jumlah jarak anggota ke centroid final ÷ jumlah anggota.')+
   panel('Jarak Antarcentroid dan Rasio',table(['Pasangan','Jarak Mij','Scatter Si','Scatter Sj','Rasio Rij'],ids.flatMap(i=>ids.filter(j=>j>i).map(j=>['C'+i+' ↔ C'+j,numberCell(d.centroid_distances[i][j],6),numberCell(d.scatter[i],6),numberCell(d.scatter[j],6),numberCell(d.ratios[i][j],6)]))),'Rij = (Si + Sj) ÷ Mij; Mij memakai jarak Euclidean antarcentroid final.')+
   panel('Maksimum dan DBI Akhir',table(['Cluster','R maksimum'],ids.map((id,i)=>['C'+id,numberCell(d.maximum_ratios[i],6)]))+'<div class="panel-body"><div class="formula">DBI = ('+d.maximum_ratios.map(v=>fmt(v,6)).join(' + ')+') / 3 = '+fmt(r.dbi,8)+'</div><p class="small muted" style="margin-top:12px">Komponen yang ditampilkan dibulatkan; nilai akhir dihitung dari presisi penuh data contoh.</p></div>');
 }
 return head('Implementasi K-Means','Telusuri lima tahap hasil analisis: normalisasi, centroid awal, iterasi, hasil akhir, dan DBI.')+
 tabs('kmeans',[['overview','Riwayat'],['normalization','Normalisasi'],['centroids','Centroid Awal'],['iterations','Iterasi'],['results','Hasil Akhir'],['dbi','Evaluasi DBI']],tab)+body;
}
export function ranking(c){
 const rows=scopedRanking(c).filter(r=>(!c.filters.cluster||r.cluster_label===c.filters.cluster)&&r.polsek_name.toLowerCase().includes((c.filters.q??'').toLowerCase()));
 const isPolres=c.role==='polres',ownRow=c.period.ranking.find(r=>r.polsek_id===c.pid);
 const rankingRows=rows.map(r=>['<strong>#'+r.rank+'</strong>',nameCell(r),label(r.cluster_label)+' '+badge('C'+r.cluster_number,'blue'),numberCell(r.score,2),numberCell(r.distance_to_centroid,4),numberCell(r.activity_total),btn('Detail','ranking-detail','data-id="'+r.polsek_id+'"','tiny')]);
 const top=isPolres?panel('Tiga Peringkat Teratas','<div class="panel-body podium">'+c.period.ranking.slice(0,3).map(r=>'<article class="podium-item"><div class="rank">'+r.rank+'</div><strong>'+esc(r.polsek_name)+'</strong><div class="score">'+fmt(r.score,2)+'</div>'+label(r.cluster_label)+'</article>').join('')+'</div>','Peringkat dan skor berdasarkan analisis dummy, bukan kinerja nyata.'):notice('Admin Polsek hanya melihat hasil unitnya sendiri, termasuk posisi unit tersebut dalam pemeringkatan 21 Polsek.');
 const extra='<div class="field"><label for="cluster">Kategori</label><select name="cluster" id="cluster">'+options([['tinggi','Kinerja Tinggi'],['sedang','Kinerja Sedang'],['rendah','Kinerja Rendah']],c.filters.cluster,'Semua kategori')+'</select></div>';
 return head('Ranking Aktivitas Polsek',isPolres?'Hasil pemeringkatan seluruh Polsek pada periode contoh.':'Hasil pemeringkatan '+own(c).name+' pada periode contoh.',btn('Ekspor contoh CSV','csv','data-kind="ranking"')+link('Laporan','reports','primary'))+
 '<section class="hero"><div><div class="eyebrow">RANKING — DATA DUMMY</div><h2>'+esc(c.period.label)+'</h2><p>Cluster + skor aktivitas publikasi; bukan penilaian kualitas konten.</p>'+badge(isPolres?'21 Polsek':own(c).name,'orange')+'</div><div class="hero-aside"><small>'+(isPolres?'Skor tertinggi':'Peringkat unit')+'</small><strong>'+(isPolres?fmt(c.period.ranking[0].score,2):'#'+ownRow.rank)+'</strong></div></section>'+
 stats(isPolres?[['Polsek','21','Dalam pemeringkatan'],['Skor tertinggi',fmt(c.period.ranking[0].score,2),'Rentang 0–100'],['Rata-rata skor',fmt(total(c.period.ranking.map(r=>r.score))/21,2),'Seluruh data dummy'],['Cluster','3','Kategori aktivitas']]:[['Peringkat','#'+ownRow.rank,'Dari 21 Polsek'],['Skor',fmt(ownRow.score,2),'Rata-rata normalisasi × 100'],['Cluster','C'+ownRow.cluster_number,'Berdasarkan aktivitas'],['Publikasi',fmt(ownRow.activity_total),'Total enam platform']])+
 top+panel(isPolres?'Daftar Ranking Polsek':'Ranking Unit', (isPolres?searchForm(c,'ranking',extra):'')+(rankingRows.length?table(['Peringkat','Polsek','Hasil Kinerja','Skor','Jarak','Total','Aksi'],rankingRows):'<p class="empty">Tidak ada hasil sesuai filter.</p>'),'Urutan: tinggi → sedang → rendah; lalu skor terbesar, jarak terkecil, dan tie-breaker deterministik.')+
 notice('Skor = rata-rata enam nilai normalisasi × 100. Label kinerja mengikuti urutan rata-rata centroid final, bukan label yang dipilih secara manual.');
}
export function reports(c){
 const rows=scopedRanking(c),isPolres=c.role==='polres',p=own(c),activity=total(rows.map(r=>r.activity_total));
 const reportRows=rows.map(r=>[String(r.rank),nameCell(r),label(r.cluster_label),numberCell(r.score,2),numberCell(r.activity_total)]);
 const clusters=isPolres?table(['Cluster','Kategori','Jumlah Polsek'],c.period.result.clusters.map(cl=>['C'+cl.cluster_number,label(cl.cluster_label),String(cl.member_count)])):'';
 return head('Laporan Aktivitas Polsek','Pratinjau laporan untuk membantu penyajian aktivitas publikasi sesuai cakupan pengguna.',btn('Cetak / Simpan PDF','print','','primary')+btn('Ekspor contoh CSV','csv','data-kind="reports"'))+
 '<section class="panel"><article class="report" id="report-document"><header class="report-title"><img src="logo-polres-subang.png" alt=""><small>SHOWCASE PORTOFOLIO • BUKAN DOKUMEN RESMI</small><h2>'+esc(isPolres?'Laporan Kinerja Kehumasan Polsek Jajaran':'Laporan Kinerja Kehumasan '+p.name)+'</h2><p>'+esc(c.period.label)+' — DATA DUMMY</p><small>Kode contoh: SHOWCASE-'+esc(c.period.id)+'-'+(isPolres?'POLRES':esc(p.code.toUpperCase()))+'</small></header>'+
 stats([['Cakupan',isPolres?'21 Polsek':'1 Polsek','Sesuai POV'],['Aktivitas',fmt(activity),'Jumlah publikasi dummy'],['Skor rata-rata',fmt(total(rows.map(r=>r.score))/rows.length,2),'Dari unit yang ditampilkan'],['Sumber','K-Means dummy','Dataset hasil generate']])+
 (isPolres?'<h3 style="margin-bottom:10px">Ringkasan Cluster</h3>'+clusters:'<p style="margin-bottom:20px">'+label(rows[0].cluster_label)+' '+badge('Peringkat #'+rows[0].rank)+'</p>')+
 '<h3 style="margin:20px 0 10px">Daftar Hasil Aktivitas</h3>'+table(['Peringkat','Polsek','Kategori','Skor','Total Publikasi'],reportRows)+
 '<div class="report-note"><strong>Catatan penggunaan.</strong> Semua angka dan hasil pada laporan ini adalah data sintetis untuk mengenalkan fitur website. Tidak digunakan untuk pelaporan operasional atau menyatakan hasil penelitian. Dalam sistem asli, hasil ranking dan laporan menjadi bahan informasi bagi Humas Polres Subang untuk penyusunan laporan kepada Polda.</div></article></section>';
}
export const analysisViews={preprocessing,kmeans,ranking,reports};
