import * as U from './ui.js';
const {esc,fmt,date,total,icon,badge,btn,link,notice,panel,table,nameCell,numberCell,label,stats,head,options,field,formNote,summary,flow,own,scopedRecaps,scopedRanking,polsekOptions,pager,chart}=U;
export function dashboard(c){
  const recaps=scopedRecaps(c),rank=scopedRanking(c),p=own(c);
  const allTotal=total(recaps.map(r=>r.total));
  const daily=Array.from({length:c.period.days},(_,i)=>total(recaps.filter(r=>Number(r.date.slice(-2))===i+1).map(r=>r.total)));
  const platformTotals=c.D.platforms.map((f,j)=>total(recaps.map(r=>r.values[j]))),max=Math.max(...platformTotals,1);
  const rows=[...recaps].reverse().slice(0,6).map(r=>[date(r.date),nameCell(c.D.polseks.find(p=>p.id===r.polsekId)),numberCell(r.total),badge('Disetujui','green'),btn('Detail','recap','data-id="'+r.id+'"','tiny')]);
  return head('Dashboard',c.role==='polres'?'Pantau aktivitas, hasil analisis, dan komunikasi seluruh Polsek.':'Ringkasan aktivitas dan informasi '+p.name+'.',link('Lihat Laporan','reports'),c.role==='polres'?'ADMIN HUMAS POLRES':'ADMIN HUMAS POLSEK')+
  '<section class="hero"><div><div class="eyebrow">Selamat datang di pratinjau portofolio</div><h2>'+esc(c.role==='polres'?'Satu sistem, seluruh alur aktivitas.':p.name)+'</h2><p>Periode contoh: '+esc(c.period.label)+' • Seluruh isi menggunakan data dummy.</p>'+badge('Read-only','blue')+badge(c.role==='polres'?'21 Polsek':'Scope: '+p.name,'orange')+'</div><div class="hero-aside"><small>Total aktivitas contoh</small><strong>'+fmt(allTotal)+'</strong><small>Enam platform media sosial</small></div></section>'+
  stats([['Polsek',c.role==='polres'?'21':'1',c.role==='polres'?'Unit dalam data contoh':'Terikat pada POV ini'],['Rekap harian',fmt(recaps.length),'Jumlah catatan pada periode'],['Total publikasi',fmt(allTotal),'Jumlah, bukan tautan konten'],[c.role==='polres'?'Cluster':'Peringkat',c.role==='polres'?'3':String(rank[0].rank),c.role==='polres'?'Hasil analisis dummy':'Posisi pada data contoh']])+
  '<div class="grid2">'+panel('Aktivitas Bulanan','<div class="panel-body">'+chart(daily)+'<div class="chart-caption"><span>1 '+esc(c.period.label)+'</span><span>'+c.period.days+' '+esc(c.period.label)+'</span></div></div>','Jumlah aktivitas dari rekap harian yang ditampilkan.')+
  panel('Aktivitas per Platform','<div class="panel-body bars">'+c.D.platforms.map((f,j)=>'<div class="bar-row"><span>'+esc(f.name)+'</span><div class="bar-track"><div class="bar-fill" style="width:'+platformTotals[j]*100/max+'%"></div></div><span class="num">'+fmt(platformTotals[j])+'</span></div>').join('')+'</div>','Total aktivitas pada enam platform.')+'</div>'+
  '<div class="grid2">'+panel('Rekap Aktivitas Terbaru',table(['Tanggal','Polsek','Publikasi','Status','Aksi'],rows),'Data dummy; tidak terhubung ke rekap operasional.',link('Semua Rekap','recaps','tiny'))+
  panel(c.role==='polres'?'Akses Cepat':'Hasil '+p.name,'<div class="panel-body">'+(c.role==='polres'?flow(['Rekap','Dataset','Normalisasi','K-Means','Laporan'])+link('Buka Preprocessing','preprocessing'):'<p>'+label(rank[0].cluster_label)+'</p><div class="list-item"><span>Skor aktivitas</span><strong>'+fmt(rank[0].score,2)+'</strong></div><div class="list-item"><span>Peringkat</span><strong>'+rank[0].rank+' / 21</strong></div>')+'<div class="list-item"><div><strong>Pesan Internal</strong><small>Percakapan dummy antar-admin</small></div>'+link('Lihat','messages','tiny')+'</div><div class="list-item"><div><strong>Pengumuman</strong><small>Informasi internal sesuai penerima</small></div>'+link('Lihat','announcements','tiny')+'</div></div>')+'</div>';
}
export function polseks(c){
 const rows=c.D.polseks.filter(p=>p.name.toLowerCase().includes((c.filters.q??'').toLowerCase())).map(p=>[esc(p.code),nameCell(p),esc(p.district),'<span class="muted small">Tidak dipublikasikan</span>',badge('Aktif','green'),esc(p.admin),btn('Detail','polsek','data-id="'+p.id+'"','tiny')+' '+btn('Pratinjau edit','polsek-edit','data-id="'+p.id+'"','tiny')]);
 return head('Kelola Polsek','Master unit dan keterkaitan Admin Polsek; identitas operator menggunakan data dummy.',btn('Pratinjau Tambah Polsek','polsek-add','','primary')+btn('Ekspor contoh CSV','csv','data-kind="polseks"'))+
 stats([['Polsek', '21','Master dari project asli'],['Aktif','21','Status untuk data showcase'],['Akun admin','21','Operator fiktif'],['Privasi Instagram','Terlindungi','ID akun tidak disertakan']])+
 panel('Daftar Polsek',searchForm(c,'polseks')+table(['Kode','Nama Polsek','Kecamatan','Instagram','Status','Admin','Aksi'],rows)+'<div class="table-foot">'+rows.length+' Polsek ditampilkan • seluruh operator adalah dummy</div>','Profil publik unit; bukan data akun operasional.');
}
export function users(c){
 const rows=c.D.polseks.filter(p=>(p.name+' '+p.admin+' '+p.username).toLowerCase().includes((c.filters.q??'').toLowerCase())).map(p=>[nameCell({name:p.admin},'Identitas fiktif'),esc(p.username),esc(p.name),esc(p.district),badge('Aktif','green'),btn('Detail','user','data-id="'+p.id+'"','tiny')+' '+btn('Pratinjau edit','user-edit','data-id="'+p.id+'"','tiny')]);
 return head('Kelola User','Pratinjau pengelolaan akun Admin Polsek. Akun dummy ini tidak dapat digunakan untuk login.',btn('Pratinjau Tambah User','user-add','','primary'))+
 stats([['Admin Polsek','21','Data operator contoh'],['Admin Polres','1','POV pratinjau'],['Akun operasional','Tidak ada','Tidak diekspor ke showcase'],['Hak akses','2 role','Polres dan Polsek']])+
 panel('Daftar Admin Polsek',searchForm(c,'users')+table(['Admin','Username','Polsek','Kecamatan','Status','Aksi'],rows),'Pengaktifan akun, penghapusan, dan reset password hanya ditampilkan sebagai pratinjau.');
}
export function searchForm(c,kind,extra=''){
 return '<form class="filters" data-filter="'+kind+'"><div class="field"><label for="search">Cari</label><input id="search" name="q" value="'+esc(c.filters.q??'')+'" placeholder="Cari nama atau informasi…"></div>'+extra+'<button class="btn primary" type="submit">Terapkan</button>'+btn('Reset','reset-filter')+'</form>';
}
export function recaps(c){
 let records=scopedRecaps(c);
 records=records.filter(r=>(!c.filters.unit||r.polsekId===Number(c.filters.unit))&&(!c.filters.from||r.date>=c.filters.from)&&(!c.filters.to||r.date<=c.filters.to)&&c.D.polseks.find(p=>p.id===r.polsekId).name.toLowerCase().includes((c.filters.q??'').toLowerCase())).sort((a,b)=>b.date.localeCompare(a.date)||a.polsekId-b.polsekId);
 const page=Math.min(c.filters.page??1,Math.max(1,Math.ceil(records.length/15)));
 const rows=records.slice((page-1)*15,page*15).map(r=>[date(r.date),nameCell(c.D.polseks.find(p=>p.id===r.polsekId)),...r.values.map(v=>numberCell(v)),numberCell(r.total),badge('Disetujui','green'),btn('Detail','recap','data-id="'+r.id+'"','tiny')]);
 let extra=c.role==='polres'?'<div class="field"><label for="unit">Polsek</label><select id="unit" name="unit">'+polsekOptions(c)+'</select></div>':'';
 extra+='<div class="field"><label for="from">Dari tanggal</label><input id="from" name="from" type="date" value="'+esc(c.filters.from??'')+'"></div><div class="field"><label for="to">Sampai tanggal</label><input id="to" name="to" type="date" value="'+esc(c.filters.to??'')+'"></div>';
 return head('Rekap Aktivitas Media Sosial','Jumlah publikasi per hari dan platform. Yang dicatat adalah angka aktivitas, bukan URL konten.',(c.role==='polres'?btn('Pratinjau Tambah Rekap','recap-add','','primary'):'')+btn('Ekspor contoh CSV','csv','data-kind="recaps"'))+
 notice(c.role==='polres'?'Sesuai versi project terbaru: rekap valid langsung berstatus <strong>Disetujui</strong>. Tidak ada alur verifikasi manual baru.':'POV Admin Polsek hanya melihat rekap <strong>'+esc(own(c).name)+'</strong>. Rekap bersifat read-only dalam implementasi terbaru.')+
 stats([['Catatan sesuai filter',fmt(records.length),'Rekap harian'],['Publikasi',fmt(total(records.map(r=>r.total))),'Jumlah enam platform'],['Scope',c.role==='polres'?'Semua Polsek':'1 Polsek','Sesuai POV pengguna'],['Platform','6','Masing-masing berupa jumlah']])+
 panel('Daftar Aktivitas Media Sosial',searchForm(c,'recaps',extra)+(rows.length?table(['Tanggal','Polsek',...c.D.platforms.map(f=>f.name),'Total','Status','Aksi'],rows):'<p class="empty">Tidak ada rekap yang sesuai filter.</p>')+pager(records.length,c,'recaps'),'Seluruh catatan pada halaman ini adalah data hasil generate.')+
 panel('Total per Platform','<div class="panel-body">'+table(['Platform','Total aktivitas'],c.D.platforms.map((f,j)=>[esc(f.name),numberCell(total(records.map(r=>r.values[j])))]))+'</div>');
}
export function crawling(c){
 return head('Crawling Instagram','Pratinjau fitur monitoring publikasi Instagram melalui Meta Graph API.',btn('Privasi pengaturan akun','instagram-settings')+btn('Pratinjau Crawling','crawl-preview','','primary')+btn('Ekspor contoh CSV','csv','data-kind="crawling"'))+
 notice('<strong>Tidak ada koneksi ke Instagram.</strong> Konten dan riwayat di bawah adalah data dummy. Token, ID akun, dan kredensial resmi tidak berada dalam bundle publik.',true)+
 stats([['Konten contoh','6','Bukan hasil API langsung'],['Riwayat contoh','2','Job fiktif'],['Koneksi API','Nonaktif','Tanpa token atau ID akun'],['Input K-Means','Rekap','Tetap dari enam platform']])+
 panel('Alur Pengambilan Data','<div class="panel-body">'+flow(['Instagram','Meta Graph API','Pengambilan data','Sistem','Basis data'])+'<p class="small muted">Pada website asli proses dijalankan di server. Showcase hanya menampilkan contoh hasil, tanpa menghubungi API.</p></div>')+
 panel('Riwayat Crawling',table(['Job','Dibuat','Rentang tanggal','Status','Hasil','Aksi'],c.D.crawlJobs.map(j=>[esc(j.id),esc(j.date),date(j.from)+' – '+date(j.to),badge(j.status,j.count?'green':'gray'),numberCell(j.count),btn('Detail','crawl-job','data-id="'+j.id+'"','tiny')])),'Semua job merupakan contoh sintetis, bukan pekerjaan yang pernah dijalankan.')+
 panel('Postingan Terbaru','<div class="panel-body post-grid">'+c.D.posts.map(p=>'<article class="post"><div class="post-type">'+icon('crawling')+esc(p.mediaType)+'</div><h3>'+esc(p.id)+'</h3><small class="muted">'+esc(p.time)+'</small><p>'+esc(p.caption)+'</p><footer><span>♥ '+p.likes+' suka</span><span>'+p.comments+' komentar</span></footer><div style="margin-top:14px">'+btn('Lihat data publikasi','post','data-id="'+p.id+'"','tiny')+'</div></article>').join('')+'</div>','Caption, jenis media, waktu, permalink, jumlah suka, dan komentar ditampilkan sebagai contoh.');
}
export function announcements(c){
 const announcements=c.D.announcements.filter(a=>c.role==='polres'||a.audience==='all'||a.target===c.pid).filter(a=>(a.title+' '+a.body).toLowerCase().includes((c.filters.q??'').toLowerCase()));
 const content=announcements.map(a=>'<article class="announcement"><h3>'+esc(a.title)+'</h3><div class="meta">'+badge(a.audience==='all'?'Semua Polsek':c.D.polseks.find(p=>p.id===a.target).name)+badge(date(a.date),'gray')+(c.role==='polres'?badge(a.readCount+' penerima membaca','green'):'')+'</div><p>'+esc(a.body)+'</p><div class="actions">'+btn('Baca lengkap','announcement','data-id="'+a.id+'"','tiny')+(c.role==='polres'?btn('Pratinjau edit','announcement-edit','data-id="'+a.id+'"','tiny'):'')+'</div></article>').join('');
 return head(c.role==='polres'?'Kelola Pengumuman':'Pengumuman','Informasi dari Admin Polres untuk seluruh Polsek atau Polsek tertentu.',c.role==='polres'?btn('Pratinjau Buat Pengumuman','announcement-add','','primary'):'')+
 notice('Seluruh pengumuman dan status baca adalah dummy. Membuka detail tidak mengirim tanda baca ke server.')+
 panel('Informasi Internal',searchForm(c,'announcements')+(content||'<p class="empty">Tidak ada pengumuman yang sesuai.</p>'),'Penerima mengikuti POV yang sedang dilihat.');
}
export function messages(c){
 const pid=c.role==='polres'?c.contact:c.pid,p=c.D.polseks.find(p=>p.id===pid),conversation=c.D.conversations.find(x=>x.polsekId===pid);
 const contacts=c.role==='polres'?'<aside class="chat-contacts" aria-label="Pilihan percakapan">'+c.D.polseks.map(p=>'<button class="chat-contact '+(p.id===pid?'active':'')+'" data-action="contact" data-id="'+p.id+'">'+esc(p.name)+'<small>'+esc(p.admin)+'</small></button>').join('')+'</aside>':'';
 const bubbles=conversation.messages.map(m=>'<div class="bubble '+(m.side===c.role?'own':'')+'"><strong>'+(m.side==='polres'?'Operator Contoh Polres':esc(p.admin))+'</strong><p>'+esc(m.body)+'</p><small>'+esc(m.time)+' • '+(m.read?'Contoh: dibaca':'Contoh: belum dibaca')+'</small></div>').join('');
 return head('Pesan Internal','Percakapan Admin Humas Polres dan Admin Humas Polsek. Seluruh percakapan adalah fiktif.')+
 notice('Pratinjau read-only: HR dapat memilih dan membaca percakapan contoh; tidak dapat mengirim atau menghapus pesan.',true)+
 panel('Percakapan Contoh','<div class="'+(c.role==='polres'?'chat-layout':'')+'">'+contacts+'<section class="chat"><header class="chat-head"><strong>'+esc(c.role==='polres'?p.name:'Admin Humas Polres')+'</strong><p class="small muted">'+esc(c.role==='polres'?p.admin:'Percakapan untuk '+p.name)+' • data dummy</p></header><div class="chat-messages">'+bubbles+'</div><form class="chat-compose"><input aria-label="Pesan tidak dapat dikirim dalam showcase" disabled placeholder="Pengiriman pesan dinonaktifkan"><button class="btn primary" disabled>Kirim</button></form></section></div>');
}
export function profile(c){
 const p=own(c),isPolres=c.role==='polres',fullName=isPolres?'Operator Contoh Polres':p.admin;
 return head('Profil','Identitas pengguna contoh dan pratinjau keamanan akun. Tidak menampilkan pengguna asli.')+
 '<section class="panel profile-summary"><div class="avatar">'+(isPolres?'AP':'AS')+'</div><div><h2>'+esc(fullName)+'</h2><p>'+esc(isPolres?'Admin Humas Polres':p.name)+'</p>'+badge('Identitas dummy','orange')+' '+badge('Aktif','green')+'</div></section>'+
 '<div class="grid-equal">'+panel('Informasi Profil','<div class="panel-body">'+formNote+'<form class="form-grid">'+field('fullName','Nama lengkap',fullName)+field('username','Username',isPolres?'demo_polres':p.username)+field('role','Role',isPolres?'Admin Humas Polres':'Admin Humas Polsek')+field('unit','Unit',isPolres?'Polres Subang':p.name)+'<div class="actions field wide"><button class="btn primary" disabled>Simpan Profil — nonaktif</button></div></form></div>')+
 panel('Keamanan Akun','<div class="panel-body"><p class="small muted">Website asli menyediakan perubahan password. Showcase tidak memiliki autentikasi operasional dan tidak menyimpan password.</p><div class="form-grid" style="margin-top:18px">'+field('oldpassword','Password saat ini','','password')+field('newpassword','Password baru','','password')+field('confirmation','Konfirmasi password','','password')+'<div class="field wide"><button class="btn" disabled>Ubah Password — nonaktif</button></div></div></div>')+'</div>';
}
export function overview(c){
 const features=[['dashboard','Ringkasan aktivitas dan akses cepat.','Keduanya'],['polseks','Master unit, profil, dan admin yang terhubung.','Polres'],['users','Pengelolaan akun Admin Polsek.','Polres'],['recaps','Jumlah publikasi harian pada enam platform.','Keduanya'],['crawling','Contoh monitoring Instagram dan riwayat job.','Polres'],['preprocessing','Dataset bulanan, normalisasi, dan riwayat snapshot.','Polres'],['kmeans','Centroid awal, iterasi, hasil cluster, dan DBI.','Polres'],['ranking','Ranking seluruh unit atau hasil unit sendiri.','Keduanya'],['reports','Ringkasan pelaporan sesuai cakupan pengguna.','Keduanya'],['announcements','Informasi umum atau khusus untuk suatu Polsek.','Keduanya'],['messages','Percakapan antar-admin sesuai unit.','Keduanya'],['profile','Profil dan pratinjau keamanan akun.','Keduanya']];
 return head('Seluruh Fitur, Dua Sudut Pandang','Peta fitur mengacu pada menu dan cakupan akses project asli.',btn('Ganti POV','switch-pov','','primary'))+
 notice('Showcase ini terpisah dari demo interaktif K-Means. Semua data dan hasil pada showcase adalah sintetis; bukan hasil penelitian atau layanan resmi kepolisian.',true)+
 '<div class="feature-grid">'+features.map(([key,text,role])=>'<article class="feature">'+icon(key)+'<h3>'+esc(U.names[key])+'</h3><p>'+esc(text)+'</p><div class="feature-role">'+badge(role==='Polres'?'Admin Polres':'Polres & Polsek',role==='Polres'?'blue':'green')+'</div>'+((c.role==='polres'||role!=='Polres')?link('Lihat Fitur',key,'tiny'):'<span class="small muted">Tersedia pada POV Admin Polres</span>')+'</article>').join('')+'</div>'+
 panel('Batas Pratinjau','<div class="panel-body">'+summary([['Dapat dilakukan','Berpindah POV, menelusuri halaman, filter, detail, pratinjau formulir, ekspor data dummy.'],['Tidak dilakukan','Menambah/mengubah data, login akun asli, mengirim pesan, menjalankan crawling, memanggil server project.'],['Privasi','Tidak menyertakan token, ID akun Instagram, password, .env, atau percakapan asli.'],['Penyimpanan','File statis; pilihan POV hanya disimpan di sesi browser.']])+'</div>','Notifikasi juga merupakan pratinjau, bukan data unread dari server.');
}
export const basicViews={dashboard,polseks,users,recaps,crawling,announcements,messages,profile,overview};
